version: '3.9'

services:

  laravel-app:
    container_name: laravel-app
    hostname: laravel.app
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
    volumes:
      - type: bind
        source: ./laravel/app
        target: /var/www/html
    ports:
      - 8080:80
    environment:
      TZ: Asia/Tokyo
